version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg_rag
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
      image: docker.n8n.io/n8nio/n8n
      container_name: n8n_sql_rag
      restart: always
      ports:
        - "5678:5678"
      volumes:
        - ./n8n_data:/home/node/.n8n
      environment:
        DB_TYPE: postgresdb
        DB_POSTGRESDB_HOST: postgres
        DB_POSTGRESDB_DATABASE: ragdb
        DB_POSTGRESDB_USER: postgres
        DB_POSTGRESDB_PASSWORD: postgres
      depends_on:
        - postgres

volumes:
  pgdata: